### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by wraza2k9** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#1]
I followed steps as per your documentation, but getting the following error during running:
AttributeError: 'PySide2.QtWidgets.QPushButton' object has no attribute 'setObjectTheme'

**Comment by KhamisiKibet** [comment]
If you are using QT Design to generate python user interface code, then remember to also import QT-PyQt-PySide-Custom-Widgets to this file.
```python 
########################################################################
# IMPORT CUSTOM BUTTONS FILE
from Custom_Widgets.widgets import *
########################################################################
```

**Comment by KhamisiKibet** [comment]
Closing since issue was solved

**Comment by hamidrajabi** [comment]
Although I have done: "from Custom_Widgets.widgets import *" ,
STILL, I have the same problem.
