### ISSUE TITLE
App closing and running in background after trying to change theme.

### ISSUE THREAD

**Issue by OldResolution** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#101]
Checking icons for Modern Teal Slate theme. Icons color: #333333
Checking icons for Midnight Teal Slate theme. Icons color: #F5F5F5
Checking icons for Modern Teal Slate theme. Icons color: #333333
Checking icons for Midnight Teal Slate theme. Icons color: #F5F5F5
Checking icons for qt designer app.
all icons have been checked and missing icons generated!
Current theme Midnight Teal Slate
('Current icons color ', '#F5F5F5', 'New icons color', '#333333')
Generating icons for your theme, please wait. This may take long
('DONE: Current icons color ', '#333333')
 After trying to change my theme the app seems to close and generates new icons eventhough its already present and then tends to keep running in the background. 
After I force stop the app and rerun it the theme changes . (Currently making project on windows)

**Comment by KhamisiKibet** [comment]
The theme is stored in settings and will be applied on app restart. You can turn off new icons generation using JSon:

```json
{
          "Theme-name": "CustomTheme2",
          "Background-color": "#F0F0F0",
          "Text-color": "#333333",
          "Accent-color": "#00FF00",
          "Icons-color": "#FFFFFF",
          "Default-Theme": false,
          "Create-icons": false
        }
```

or

```json
{
  "CheckForMissingicons": false
}
```
