### ISSUE TITLE
SVG icons not loading

### ISSUE THREAD

**Issue by Za3tour420** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#108]
I'm facing an issue loading my .svg icons when running 'main.py'.
![1](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/100478662/2bdb6349-36d6-4925-9dff-ecadd2439e7a)
![2](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/100478662/8b1fbd03-4692-4a84-b4ce-9a8ba89c9a75)
![3](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/100478662/37045f34-a928-4730-9555-5999c6bf44b4)
![4](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/100478662/865abd05-d318-46a3-8fbd-053b2c1070ee)
![5](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/100478662/ce1656c9-76c1-456d-9aee-ca031977a46e)

I converted my interface file using the command 'Custom_Widgets --convert-ui ui/interface.ui'.

Here's my json-styles/style.json code :

`{
	"QMainWindow":[
		{
			"tittle":"Optichain",
			"icon":"Qss/icons/images/logo.jpg",
			"frameless": true,
			"transluscentBg": true,
			"sizeGrip": "sizeGrip",
			"navigation":[
				{
					"minimize":"minimizeBtn",
					"close": "closeBtn",
					"restore":[
						{	
							"buttonName": "restoreBtn",
							"normalIcon": "Qss/icons/icons/square.svg",
							"maximizedIcon": "Qss/icons/icons/copy.svg"
						}
					],
					"moveWindow": "headerContainer",
					"tittleBar": "headerContainer"
				}
			]
		}
	]
}`

Here's my main.py code : 
![6](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/100478662/b6fbbf98-0ded-43c0-9d2a-a56337c468c8)

Github won't let me put my code correctly so there's the screenshot.

Any suggested fix ?

P.S: The "TEST CUSTOM" folder is unrelated, it's just me testing the package and it's working.

Python Version : 3.10
QT Library : PySide6
Custom_Widgets Version : 0.9.6

**Comment by ArmaganUyanik** [comment]
You should be using the relative path from the .qrc file not the .py file. Also the path name should include prefix name as well so the path to your .svg files would look something like ":/*prefix*/icons/*name*.svg". You can also make sure that your path is always correct by copying the path of the specific icon in the resource browser of Qt Designer.
