### ISSUE TITLE
issue with normal icon and maximized icon did not switch in style.json

### ISSUE THREAD

**Issue by baya0** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#110]
while loading style.json the widget appeared but the icons in navigation like restorBtn and the menuBtn did not switch between normalicon or maximizeicon 
i am using pyside6  and i checked the paths ..also can  i add events to this buttons only ? or it might cause an error ..
 here is the code 
of style.json

{
	"QMainWindow":[
		{
			
			"icon":":/images/images/images/log.png",
			"frameless": true,
			"transluscentBg": true,
			"sizeGrip": "sizeGrip",

			"navigation":[
				{
					"minimize":"minimizeBtn",
					"close": "closeBtn",
					"restore":[
						{	
							"buttonName": "restoreBtn",
							"normalIcon": ":/icons/images/icons/icon_maximize.png",
							"maximizedIcon": ":/icons/images/icons/icon_restore.png"
						}
					],
					"moveWindow": "headerContainer",
					"tittleBar": "headerContainer"
				}
			]
		}
	],

	"QCustomSlideMenu": [{
		"name": "LeftMenuContainer",
		"defaultSize": [{
			"width": 48,
			"height": "parent"
		}],
		"collapsedSize": [{
			"width": 48,
			"height": "parent"
		}],
		"expandedSize": [{
			"width": 120,
			"height": "parent"
		}],
		"toggleButton": [{
			"buttonName": "menuBtn",
			"icons": [{
				"whenMenuIsCollapsed": ":/icons/images/icons/icon_menu.png",
				"whenMenuIsExpanded": ":/icons/images/icons/cil-chevron-left.png"
			}]
		}],
		"menuTransitionAnimation": [{
			"animationDuration": 500,
			"animationEasingCurve": "Linear"
		}]
	},

	{
		"name": "centerMenuContainer",
		"defaultSize": [{
			"width": 0,
			"height": "parent"
		}],
		"collapsedSize": [{
			"width": 0,
			"height": "parent"
		}],
		"expandedSize": [{
			"width": 200,
			"height": "parent"
		}],
		"menuTransitionAnimation": [{
			"animationDuration": 500,
			"animationEasingCurve": "Linear"
		}]
	}

]
}

**Comment by KhamisiKibet** [comment]
Update the custom widgets module.
