### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by wish2333** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#112]
“”“
TypeError: 'PySide6.QtWidgets.QHBoxLayout.__init__' called with wrong argument types:
  PySide6.QtWidgets.QHBoxLayout.__init__(QFrame)
Supported signatures:
  PySide6.QtWidgets.QHBoxLayout.__init__()
  PySide6.QtWidgets.QHBoxLayout.__init__(PySide6.QtWidgets.QWidget)
PS Q:\Git\FFmpeg-python\PyQt-Fluent-Widgets-Gallery\Modern_GUI_PyDracula_PySide6_or_PyQt6-master> 
”“”
What‘s the matter? I'll be appreciated if you can help.

**Comment by KhamisiKibet** [comment]
This is not a custom widgets error, can you provide more information/code?
