### ISSUE TITLE
PyInstaller Error: Conflict Between PyQt and PySide in Custom_Widgets

### ISSUE THREAD

**Issue by turkanispak** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#117]
**Description:**
I'm encountering an issue with the `Custom_Widgets` library when trying to create a standalone executable using PyInstaller. The problem arises due to the use of both PyQt and PySide within the library, leading to conflicts during the packaging process.

**Steps to Reproduce:**
1. Created a Python project using the `Custom_Widgets` library.
2. Attempted to create a standalone executable using PyInstaller with the following command:
   ```bash
   pyinstaller --onefile --windowed main.py
   ```
3. Encountered the following error during the PyInstaller build process:
   ```
   Aborting build process due to attempt to collect multiple Qt bindings packages: attempting to run hook for 'PyQt6', while hook for 'PySide6' has already been run! PyInstaller does not support multiple Qt bindings packages in a frozen application - either ensure that the build environment has only one Qt bindings package installed, or exclude the extraneous bindings packages via the module exclusion mechanism (--exclude command-line option, or excludes list in the spec file).
   ```

**Steps Taken to Resolve the Issue:**
1. **Identified the Conflict**: Realized that the use of both PyQt and PySide within the `Custom_Widgets` library was causing the conflict.
2. **Uninstalled PyQt**: Attempted to resolve the issue by uninstalling PyQt to ensure only PySide is used.
   ```bash
   pip uninstall PyQt6
   ```
3. **Updated Imports**: Modified all import statements in my project to exclusively use PySide6 instead of QtPy, PyQt, or any other bindings.

   Examples:
   ```python
   from PySide6.QtCore import Qt, QRect, QSettings, QPropertyAnimation, QSize
   from PySide6.QtGui import QColor, QPaintEvent, QPainter, QResizeEvent
   from PySide6.QtWidgets import QWidget, QGraphicsDropShadowEffect, QStyleOption, QStyle
   ```
4. **Modified Spec File**: Ensured all necessary files and resources are included in the PyInstaller spec file.
   ```python
   # -*- mode: python ; coding: utf-8 -*-

   import sys
   import os
   import Custom_Widgets

   custom_widgets_path = os.path.dirname(Custom_Widgets.__file__)

   block_cipher = None

   a = Analysis(
       ['main.py'],
       pathex=['.', os.path.join(sys.prefix, 'Lib', 'site-packages')],
       binaries=[],
       datas=[
           ('generated-files/css/main.css', 'generated-files/css'),
           ('generated-files/json/interface.json', 'generated-files/json'),
           ('generated-files/ui/new_interface.ui', 'generated-files/ui'),
           ('json-styles/style.json', 'json-styles'),
           ('logs/custom_widgets.log', 'logs'),
           ('Qss/icons/*', 'Qss/icons'),
           ('Qss/scss/*', 'Qss/scss'),
           (custom_widgets_path, 'Custom_Widgets'),
       ],
       hiddenimports=[
           'Custom_Widgets',
           'Custom_Widgets.AnalogGaugeWidget',
           'Custom_Widgets.CMD',
           'Custom_Widgets.FileMonitor',
           'Custom_Widgets.Log',
           'Custom_Widgets.ProgressIndicator',
           'Custom_Widgets.ProjectMaker',
           'Custom_Widgets.QAppSettings',
           'Custom_Widgets.QCustomAnnotationWidget',
       ],
       hookspath=[],
       hooksconfig={},
       runtime_hooks=[],
       excludes=[],
       noarchive=False,
       optimize=0,
   )

   pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

   exe = EXE(
       pyz,
       a.scripts,
       a.binaries,
       a.zipfiles,
       a.datas,
       [],
       name='my_app',
       debug=False,
       bootloader_ignore_signals=False,
       strip=False,
       upx=True,
       upx_exclude=[],
       runtime_tmpdir=None,
       console=False,
       disable_windowed_traceback=False,
       argv_emulation=False,
       target_arch=None,
       codesign_identity=None,
       entitlements_file=None,
   )

   coll = COLLECT(
       exe,
       a.binaries,
       a.zipfiles,
       a.datas,
       strip=False,
       upx=True,
       upx_exclude=[],
       name='my_app'
   )
   ```

**Current Status:**
Despite these steps, I am still encountering issues when running the generated executable. Specifically, I get a `FileNotFoundError` for SCSS files that should be included and an `AttributeError` regarding missing attributes in the `Ui_MainWindow` class.

**Request:**
Could you please provide guidance on:
1. How to properly configure `Custom_Widgets` to use only PySide6 or only PyQt6 without causing conflicts?
2. Any additional steps or best practices for resolving conflicts between PyQt and PySide in the context of using PyInstaller.

**Note:** I have also modified the library files to utilize PySide6 accordingly, I do not use any custom themes so I think if I could get around the error thrown by SassCompiler.py, I can get the solution to work.
Thank you for your assistance!

**Comment by vudat199812** [comment]
I'm also in this situation, what should I do?

**Comment by turkanispak** [comment]
**Resolution:**

Following the guidance from the library's author, I resolved the PyQt and PySide conflicts by ensuring my project exclusively uses PySide6. Additionally, the author's advice on **copying necessary static files to the executable's folder after generation** was what solved the issue for me. This step, as detailed in the GitHub guide and YouTube tutorial linked below, fixed remaining issues related to file handling and UI attributes.

- GitHub Guide: [24-Modern-Desktop-GUI](https://github.com/KhamisiKibet/24-Modern-Desktop-GUI)
- YouTube Tutorial: [Watch Here](https://www.youtube.com/watch?v=JK-B-CT34EU)

Thanks for the support!
