### ISSUE TITLE
OSError: no library called "cairo-2" was found

### ISSUE THREAD

**Issue by Ehsan125** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#13]
I am using PYQT-6 , and PYQT5 Pyside2 and Pyside2  on windows 10, while running the following code : 

```
########################################################################
## SPINN DESIGN CODE
# YOUTUBE: (SPINN TV) https://www.youtube.com/spinnTv
# WEBSITE: spinndesign.com
########################################################################

########################################################################
## IMPORTS
########################################################################

import os
import sys
from PySide2 import *
from PySide6 import *
#import json



########################################################################
# IMPORT GUI FILE
from ui_Dashboard_Finance import *
########################################################################

########################################################################
# IMPORT Custom widgets
from Custom_Widgets.Widgets import *
########################################################################


########################################################################
## MAIN WINDOW CLASS
########################################################################
class MainWindow(QMainWindow):
    def __init__(self):
        QMainWindow.__init__(self)
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        ########################################################################
        # APPLY JSON STYLESHEET
        ########################################################################
        # self = QMainWindow class
        # self.ui = Ui_MainWindow / user interface class
        loadJsonStyle(self, self.ui)
        ########################################################################

        ########################################################################

        self.show()


########################################################################
## EXECUTE APP
########################################################################
if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()
    sys.exit(app.exec_())
########################################################################
## END===>
###########################################
```#############################  

I am getting the following error 

```
Traceback (most recent call last):
  File "f:\Development\desktop\OCR_Keyboard\main.py", line 26, in <module>
    from Custom_Widgets.Widgets import *
  File "F:\Development\desktop\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "F:\Development\desktop\lib\site-packages\Custom_Widgets\Widgets.py", line 19, in <module>
    from .Qss import SassCompiler
  File "F:\Development\desktop\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "F:\Development\desktop\lib\site-packages\Custom_Widgets\Qss\SassCompiler.py", line 20, in <module>
    from . SvgToPngIcons import NewIconsGenerator
  File "F:\Development\desktop\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "F:\Development\desktop\lib\site-packages\Custom_Widgets\Qss\SvgToPngIcons.py", line 1, in <module>
    import cairosvg
  File "F:\Development\desktop\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "F:\Development\desktop\lib\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
  File "F:\Development\desktop\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "F:\Development\desktop\lib\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "F:\Development\desktop\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "F:\Development\desktop\lib\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "F:\Development\desktop\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
```



i have used these two following solution but all in vain: 

[Solution 1](https://stackoverflow.com/questions/38556368/getting-oserror-dlopen-failed-to-load-a-library-cairo-cairo-2-on-windows)

[Solution 2](https://stackoverflow.com/questions/43449436/oserror-cannot-load-library-libcairo-so-2-error-0x7e-additionally-ctypes-uti?rq=1)

Please needful help is required.

**Comment by KhamisiKibet** [comment]
Try this https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/issues/8#issuecomment-1059163661

**Comment by slip686** [comment]
I have similar issue, but on Apple M1 chip. If I put 'libcairo.2.dylib' to project folder I'm getting following:

> cannot load library 'libcairo.so.2': dlopen(libcairo.so.2, 0x0002): tried: 'libcairo.so.2' (no such file), '/usr/lib/libcairo.so.2' (no such file), '/Users/slip686/interface/libcairo.so.2' (no such file), '/usr/lib/libcairo.so.2' (no such file)
**> cannot load library 'libcairo.2.dylib': dlopen(libcairo.2.dylib, 0x0002): tried: 'libcairo.2.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/lib/libcairo.2.dylib' (no such file), **'/Users/slip686/interface/libcairo.2.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/lib/libcairo.2.dylib' (no such file)****
> cannot load library 'libcairo-2.dll': dlopen(libcairo-2.dll, 0x0002): tried: 'libcairo-2.dll' (no such file), '/usr/lib/libcairo-2.dll' (no such file), '/Users/slip686/interface/libcairo-2.dll' (no such file), '/usr/lib/libcairo-2.dll' (no such file)

Cairo libs installed via Ports, seems like it is the last version for Apple M1 chip. 
Is there any suggestions for this problem?
