### ISSUE TITLE
ERROR: TypeError: setWindowIcon(self, QIcon): argument 1 has unexpected type 'PySide2.QtGui.QIcon'

### ISSUE THREAD

**Issue by Estheiler** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#16]
Hello, I am trying to apply the style to PyQt5 but I have not been able to, apparently I am mixing Pyside with PyQt. Can anybody help me?

`
import sys
import os

from Custom_Widgets.Widgets import *

from gui.uis.main_interfaz import Ui_MainWindow

from PyQt5.QtWidgets import QMainWindow, QApplication, QWidget, QDialog
import math

class VentanaPrincipal(QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        QMainWindow.__init__(self, parent)
        self.setupUi(self)
        

        # APPLY JSON STYLESHEET
        
        # self = QMainWindow class
        self.ui = Ui_MainWindow() #/ user interface class
        loadJsonStyle(self, self.ui)
     
if __name__ == "__main__":
    app = QApplication([])
    window = VentanaPrincipal()
    window.show()
    app.exec_()
`

**Comment by KhamisiKibet** [comment]
Use pyside2 only, don't mix
