### ISSUE TITLE
[improvment] Change PyQt/Pyside dependencies to qtpy

### ISSUE THREAD

**Issue by raylemon** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#22]
To avoid problems with dependencies to PyQt, PySide, maybe you should change deps to qtpy

**Comment by emcek** [comment]
#41

**Comment by KhamisiKibet** [comment]
QT-PyQt-PySide-Custom-Widgets 0.6.4 supports both pyqt and pyside
