### ISSUE TITLE
NameError: name 'sys' is not defined

### ISSUE THREAD

**Issue by IwanBD** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#23]
After installing the library QT-PyQt-PySide-Custom-Widgets, I run the command `from Custom_Widgets.ProgressIndicator import test` in the terminal I get  the following errors: 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/iwan/.local/lib/python3.8/site-packages/Custom_Widgets/ProgressIndicator/test.py", line 23, in <module>
    from Custom_Widgets.ProgressIndicator.ui_interface import *
  File "/home/iwan/.local/lib/python3.8/site-packages/Custom_Widgets/ProgressIndicator/ui_interface.py", line 10, in <module>
    if 'PySide2' in sys.modules:
NameError: name 'sys' is not defined`
I use Python 3.8.10 version and I tried it on Ubuntu 20.04.4 LTS and Windows 11

**Comment by argaiv91** [comment]
Exactly the same here! hopefully they get it fixed soon, it looks amazing !! (sorry I'm not the answer you're waiting for)

**Comment by IwanBD** [comment]
Ok but still thanks for your answer

**Comment by sharin974** [comment]
I used to have same error and i manage to bypass it by downgrade to 0.6.1 using

 pip install --upgrade QT-PyQt-PySide-Custom-Widgets==0.6.1


And having python 8.5 and gtk as mentioned here : https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/issues/8#issuecomment-1059163661


Be careful with 32bit or 64bit both have to be the same arch 

I dont try with new version of python or last version of this plugin.

Hope be enough helpful

And sorry if my english not so good hope you understand what i've wrote

**Comment by IwanBD** [comment]
Yes, I understand your explanations well, I don't have much luck with English either. I tested it and it works fine, really thanks for sharing, I was really looking for this solution and fortunately I found you. Thanks again for your help.

**Comment by argaiv91** [comment]
My man !!!! Sorry for the late reply, I put it aside for a while cause I was very frustrated and I finally decided to give it another try. I followed your instructions and it works perfectly with Python 9.5.
I'm not native English speaker either but I understand your explanation perfectly. Thank you so much man and obviously a huge thank you to the creator !!

**Comment by knuwe1** [comment]
Hi great job done!!! Fixed the problem for me too ... thanks a lot

**Comment by KhamisiKibet** [comment]
Solved, update the module
