### ISSUE TITLE
How can i install  QT-PyQt-PySide-Custom-Widgets on rasapberry 4

### ISSUE THREAD

**Issue by Prashant-Aviskaran** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#26]
I am trying to install QT-PyQt-PySide-Custom-Widgets on the raspberry 4 B model but it is not supported.

**Comment by KhamisiKibet** [comment]
Try this https://raspberrytips.com/install-python-packages-on-raspberry-pi/
