### ISSUE TITLE
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

### ISSUE THREAD

**Issue by Prashant-Aviskaran** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#27]
ERROR: Cannot install qt-pyqt-pyside-custom-widgets==0.0.8, qt-pyqt-pyside-custom-widgets==0.0.9, qt-pyqt-pyside-custom-widgets==0.1.0, qt-pyqt-pyside-custom-widgets==0.1.1, qt-pyqt-pyside-custom-widgets==0.1.2, qt-pyqt-pyside-custom-widgets==0.1.3, qt-pyqt-pyside-custom-widgets==0.1.4, qt-pyqt-pyside-custom-widgets==0.1.5, qt-pyqt-pyside-custom-widgets==0.1.6, qt-pyqt-pyside-custom-widgets==0.1.7, qt-pyqt-pyside-custom-widgets==0.1.8, qt-pyqt-pyside-custom-widgets==0.1.9, qt-pyqt-pyside-custom-widgets==0.2.0, qt-pyqt-pyside-custom-widgets==0.2.1, qt-pyqt-pyside-custom-widgets==0.2.2, qt-pyqt-pyside-custom-widgets==0.2.3, qt-pyqt-pyside-custom-widgets==0.2.4, qt-pyqt-pyside-custom-widgets==0.2.5, qt-pyqt-pyside-custom-widgets==0.2.6, qt-pyqt-pyside-custom-widgets==0.3.1, qt-pyqt-pyside-custom-widgets==0.3.2, qt-pyqt-pyside-custom-widgets==0.3.6, qt-pyqt-pyside-custom-widgets==0.3.7, qt-pyqt-pyside-custom-widgets==0.3.8, qt-pyqt-pyside-custom-widgets==0.3.9, qt-pyqt-pyside-custom-widgets==0.4.1, qt-pyqt-pyside-custom-widgets==0.4.3, qt-pyqt-pyside-custom-widgets==0.4.6, qt-pyqt-pyside-custom-widgets==0.4.8, qt-pyqt-pyside-custom-widgets==0.4.9, qt-pyqt-pyside-custom-widgets==0.5.0, qt-pyqt-pyside-custom-widgets==0.5.1, qt-pyqt-pyside-custom-widgets==0.5.2, qt-pyqt-pyside-custom-widgets==0.5.3, qt-pyqt-pyside-custom-widgets==0.5.4, qt-pyqt-pyside-custom-widgets==0.5.5, qt-pyqt-pyside-custom-widgets==0.5.6, qt-pyqt-pyside-custom-widgets==0.5.7, qt-pyqt-pyside-custom-widgets==0.5.8, qt-pyqt-pyside-custom-widgets==0.5.9, qt-pyqt-pyside-custom-widgets==0.6.0, qt-pyqt-pyside-custom-widgets==0.6.1, qt-pyqt-pyside-custom-widgets==0.6.2 and qt-pyqt-pyside-custom-widgets==0.6.3 because these package versions have conflicting dependencies.

**Comment by flamesjames** [comment]
Any fix for this? I'm getting the same.
