### ISSUE TITLE
Hi I am facing this error

### ISSUE THREAD

**Issue by paxsipornax** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#28]
OSError: no library called "cairo-2" was found
no library called "cairo" was found
cannot load library 'C:\Program Files (x86)\GTK2-Runtime\bin\libcairo-2.dll': error 0xc1
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0xc1

 pip install I installed QT-PyQt-PySide-Custom-Widgets

**Comment by Parsa-Barandaf** [comment]
Hi , download GTK From [This Repository](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases) and install that , your Error will be fixed.
