### ISSUE TITLE
Pyqt6 and pyside6

### ISSUE THREAD

**Issue by rishuriya** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#32]
TypeError: 'PySide2.QtWidgets.QWidget' called with wrong argument types:
  PySide2.QtWidgets.QWidget(QFrame)
Supported signatures:
  PySide2.QtWidgets.QWidget(typing.Optional[PySide2.QtWidgets.QWidget] = None, PySide2.QtCore.Qt.WindowFlags = Default(Qt.WindowFlags))

**Comment by muchangdian** [comment]
Maybe you use the pyqt5 module?

**Comment by muchangdian** [comment]
> TypeError：使用错误的参数类型调用“PySide2.QtWidgets.QWidget”： PySide2.QtWidgets.QWidget(QFrame) 支持的签名： PySide2.QtWidgets.QWidget(typing.Optional[PySide2.QtWidgets.QWidget] = None, PySide2.QtCore.Qt .WindowFlags = 默认（Qt.WindowFlags））

Maybe you use the pyqt module?

**Comment by emcek** [comment]
#41

**Comment by KhamisiKibet** [comment]
QT-PyQt-PySide-Custom-Widgets 0.6.4 supports both pyqt and pyside

**Comment by emcek** [comment]
Can you show `pip list` ?
