### ISSUE TITLE
is not better to stay on PySide2?

### ISSUE THREAD

**Issue by EmadDeve20** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#36]
Pyside6 is not working for me and I got an error like this: NameError: Error evaluating `PySide6.QtWidgets.QWidget.__init__`: name 'PySide6' is not defined

I search it And I [Found](https://stackoverflow.com/questions/71636262/nameerror-error-evaluating-pyside6-qtwidgets-qwidget-init-name-pyside6)

yes, I did it before I see this link. so I think just using pyside2 for now is better. I must always change PySide6 to PySide2 :(

**Comment by emcek** [comment]
#41

**Comment by KhamisiKibet** [comment]
Now should work with pyside 6 and pyqt6
