### ISSUE TITLE
minimize and sizeGrip on macOS

### ISSUE THREAD

**Issue by grugnoymeme** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#37]
Hi i'm here cauze, as from title, the app is working fine, except the "minimize" button that's not doin' its job, and the sizeGrip, as well, not working at all. It's a problem of macOS or i've missing something? 
i cannot understand also why when i try to view the python code, inside Qt Designer: FORM --> VIEW CODE, i recive an alert: Unable to launch /anaconda3/bin/uic (this append both having conda3 installed or not).

 please help meeeee!!!! thank to everyone on u!

**Comment by grugnoymeme** [comment]
i cannot understand also why when i try to view the python code, inside Qt Designer: FORM --> VIEW CODE, i recive an alert: Unable to launch /anaconda3/bin/uic (this append both having conda3 installed or not)... this is not a real problem, cause i convert the interface.ui file fron terminal using pyuic5 comand, but it would great can do it b y the software (qt designer) cause every time i change something, n addition to overwriting the file, i need to change the first line on ui_interface.py (import PyQt5..... to import PySide2) otherwise not work... please help meeeee!!!! thank to everyone on u!

**Comment by DoubleChuang** [comment]
I have the same issue(minimize and sizeGrip are not work) on MacOS 13

**Comment by grugnoymeme** [comment]
no closed... why???? not completed...
