### ISSUE TITLE
Installation error on Ubuntu.

### ISSUE THREAD

**Issue by judsonbishop** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#4]
jud@qt-devel:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
jud@qt-devel:~$ pip3 install QT-PyQt-PySide-Custom-Widgets
Collecting QT-PyQt-PySide-Custom-Widgets
  Using cached QT-PyQt-PySide-Custom-Widgets-0.3.9.tar.gz (60 kB)
Collecting PyQt5
  Using cached PyQt5-5.15.6-cp36-abi3-manylinux1_x86_64.whl (8.3 MB)
Requirement already satisfied: PySide2 in ./.local/lib/python3.8/site-packages (from QT-PyQt-PySide-Custom-Widgets) (5.15.2)
Collecting cairosvg
  Using cached CairoSVG-2.5.2-py3-none-any.whl (45 kB)
ERROR: Could not find a version that satisfies the requirement codecs (from QT-PyQt-PySide-Custom-Widgets) (from versions: none)
ERROR: No matching distribution found for codecs (from QT-PyQt-PySide-Custom-Widgets)

**Comment by KhamisiKibet** [comment]
Try Pip instead of Pip3

**Comment by judsonbishop** [comment]
jud@qt-devel:~$  pip install QT-PyQt-PySide-Custom-Widgets
Collecting QT-PyQt-PySide-Custom-Widgets
  Using cached QT-PyQt-PySide-Custom-Widgets-0.3.9.tar.gz (60 kB)
Collecting PyQt5
  Using cached PyQt5-5.15.6-cp36-abi3-manylinux1_x86_64.whl (8.3 MB)
Requirement already satisfied: PySide2 in ./.local/lib/python3.8/site-packages (from QT-PyQt-PySide-Custom-Widgets) (5.15.2)
Collecting cairosvg
  Using cached CairoSVG-2.5.2-py3-none-any.whl (45 kB)
ERROR: Could not find a version that satisfies the requirement codecs (from QT-PyQt-PySide-Custom-Widgets) (from versions: none)
ERROR: No matching distribution found for codecs (from QT-PyQt-PySide-Custom-Widgets)

**Comment by KhamisiKibet** [comment]
Try 
```
pip install --upgrade pip
```
Then 
```
pip install QT-PyQt-PySide-Custom-Widgets
```

**Comment by judsonbishop** [comment]
Thank you for taking the time, that did not work either.

jud@qt-devel:~$ pip install --upgrade pip
Collecting pip
  Downloading pip-22.0.3-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 436 kB/s 
Installing collected packages: pip
Successfully installed pip-22.0.3
jud@qt-devel:~$ pip install QT-PyQt-PySide-Custom-Widgets
Collecting QT-PyQt-PySide-Custom-Widgets
  Using cached QT-PyQt-PySide-Custom-Widgets-0.3.9.tar.gz (60 kB)
Collecting PyQt5
  Using cached PyQt5-5.15.6-cp36-abi3-manylinux1_x86_64.whl (8.3 MB)
Requirement already satisfied: PySide2 in ./.local/lib/python3.8/site-packages (from QT-PyQt-PySide-Custom-Widgets) (5.15.2)
Collecting cairosvg
  Using cached CairoSVG-2.5.2-py3-none-any.whl (45 kB)
ERROR: Could not find a version that satisfies the requirement codecs (from QT-PyQt-PySide-Custom-Widgets) (from versions: none)
ERROR: No matching distribution found for codecs (from QT-PyQt-PySide-Custom-Widgets)

**Comment by KhamisiKibet** [comment]
Okay, let me see if I can solve it. 
For now, go to this link https://spinntv.com/designs/MxBnOjsm#
Download the attached zip, extract the files, then copy the "Custom_Widgets" folder to the root directory of your project, that should work

**Comment by judsonbishop** [comment]
Thank you, will do.

**Comment by KhamisiKibet** [comment]
The issue has been solved, please install the latest version
```
pip install QT-PyQt-PySide-Custom-Widgets>=0.5.6
```
