### ISSUE TITLE
The error after installing the package  'libxcb.dll'

### ISSUE THREAD

**Issue by NajwaRabe** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#42]
I got an error after installing the package first, Cairo Library ... After installing it, this error appeared in this library

lib = ffi.dlopen(soname)
OSError: cannot load library 'libxcb.dll': error 0x7e

**Comment by KhamisiKibet** [comment]
Follow this [thread](https://github.com/Kozea/WeasyPrint/issues/475)
