### ISSUE TITLE
Project Builder/Project Setup Wizard

### ISSUE THREAD

**Issue by Ghotic190** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#45]
Hello i was trying create demo app by your project maker : https://khamisikibet.github.io/QT-PyQt-PySide-Custom-Widgets/docs/project-maker.html

And i got stuck on this error "
```
ubuntu@ubuntu-VirtualBox:~/Desktop/Test/QtPyUi$ python3 main.py

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

Traceback (most recent call last):

  File "/home/ubuntu/Desktop/Test/QtPyUi/main.py", line 66, in <module>

    window = MainWindow()

  File "/home/ubuntu/Desktop/Test/QtPyUi/main.py", line 31, in __init__

    self.ui.setupUi(self)

  File "/home/ubuntu/Desktop/Test/QtPyUi/ui_interface.py", line 53, in setupUi

    self.centralwidget = QWidget(MainWindow)

TypeError: 'PySide2.QtWidgets.QWidget' called with wrong argument types:

  PySide2.QtWidgets.QWidget(MainWindow)

Supported signatures:

  PySide2.QtWidgets.QWidget(typing.Optional[PySide2.QtWidgets.QWidget] = None, PySide2.QtCore.Qt.WindowFlags = Default(Qt.WindowFlags))
```

I was trying follow steps in this video also : https://www.youtube.com/watch?v=adC48qZ8p5Y&t=3150s

but get same error when i was importing custom widgets.

**Comment by HongruiTang** [comment]
I got the same error

**Comment by koOffee** [comment]
Same issue as well. Any suggestions guys?

**Comment by koOffee** [comment]
Guys, simple solution is to change import in QSS_Resources_rc.py. I suppose it should be:

`from PySide2 import QtCore`

instead of

`from PyQt5 import QtCore`.

This will help to get rid of all conflicts between classes of PyQt and Pyside2.
