### ISSUE TITLE
QPushButton error

### ISSUE THREAD

**Issue by hoerilahyar** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#5]
I got error in your example  : https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/tree/main/examples/QPushButtons

File "Custom_Widgets\Widgets.py", line 2099, in loadJsonStyle
    raise Exception(buttonObject.metaObject().className(), buttonObject, " is not of type QPushButton")
Exception: ('QPushButton', <PySide2.QtWidgets.QPushButton(0x2b8a83d5370, name="exitBtn") at 0x000002B8A9CB3DC0>, ' is not of type QPushButton')

**Comment by KhamisiKibet** [comment]
Youre using a widget that is not a QPushButton, check your widget.
