### ISSUE TITLE
QStacked Widgets don't work after building with pyinstaller.

### ISSUE THREAD

**Issue by xtatik01** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#51]
After creating an exe file with pyinstaller, no button works. I see the finger instead of the arrow but nothing happens when I click. Yet everything was working fine before the build.

**Comment by ovclara** [comment]
I am also trying to convert to exe using pyinstaller yet I am not able to do it- It says -import 'Custom-Widgets' not found

How dis you manage to create the exe? 
I used below :
pyinstaller --noconfirm --onedir --console --hidden-import "Custom-Widgets" --hidden-import "PySide2" --hidden-import "tornado"  "D:/PySIDE6/22-Modern-UI/main.py"

**Comment by pdnguyen179** [comment]
Did you use one-file mode?
I stuck with "Ui_MainWindow" object has no attribute "themes".....
I have no idea how to compile my project to exe file =((((((((

**Comment by kyleb-92** [comment]
Any updates on this issue? Same problem occured from my side, once the exe was created, all the custom widgets became unresponsive.
