### ISSUE TITLE
 No module named 'PySide2'

### ISSUE THREAD

**Issue by Samnessi** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#55]
from PySide2.QtCore import *  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'PySide2'

**Comment by MrAmmia** [comment]
Pip install PySide2 in your terminal to install PySide2

**Comment by yougurty** [comment]
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
报这样的错误

**Comment by 28Rasl** [comment]
Pyside is not supported on the latest python version(3.11 and later). Use or reinstall Python 3.10. After reinstalling python, your venv will try to use the old python. To do this, you need to activate your virtual environment again.
