### ISSUE TITLE
Keeps Trying to Generate Icons Every time I open the app.

### ISSUE THREAD

**Issue by xmusicxmakerx** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#57]
After applying the theme and commenting out the code for applying the theme, every time I open run main.py it tries to generate new icons again. The only way I have found to stop it from trying to generate the icons again is to comment out 

QAppSettings.updateAppSettings(self)

Of course when I do that the theme disappears. 

       
      <# # Apply Theme to the application
        QAppSettings.updateAppSettings(self)
        # settings = QSettings()
        # # # CHANGE THE THEME NAME IN SETTINGS
        # # Use one of the app themes from your JSON file
        # settings.setValue("THEME", "Default-Dark")
        # #
        # # # RE APPLY THE NEW SETTINGS
        # # # CompileStyleSheet might also work
        # # # CompileStyleSheet.applyCompiledSass(self)
        # QAppSettings.updateAppSettings(self)>

.........\QSS\main.py" 
Current icons color  None New icons color #fff
Generating icons for your theme, please wait. This may take long

Process finished with exit code 0

**Comment by KhamisiKibet** [comment]
That may be an os problem, your app settings are not being saved.
