### ISSUE TITLE
Confusing instructions: from Custom_Widgets.ProgressIndicator should be run from a python3 shell

### ISSUE THREAD

**Issue by bezunartea** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#58]
I'm running Linux Mint, python 3 .8.10, and after successfully running "pip install QT-PyQt-PySide-Custom-Widgets", I try to follow the **Installation Testing** that state that I should _Run this from your terminal or create a python file:_ `from Custom_Widgets.ProgressIndicator import test` ... but "from" is not a valid shell command!

I suggest changing the test instructions to: Create a file test.py with the following code: 

`from Custom_Widgets.ProgressIndicator import test`
`test.main()`

Run it from the command line with `python3 test.py`

One last thing: The test still didn't run after running `pip install PySide6` but did after `pip install PySide2`

Thanks for your all your work!

**Comment by KhamisiKibet** [comment]
Latest update provides the example code in the repository, just clone it or download the zip file
