### ISSUE TITLE
Testing issue

### ISSUE THREAD

**Issue by PiodaP** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#60]
Texts were black and the interface wasn`t exactly like the one showed. Is it normal?
![20230511225540](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/130636780/5690f543-9d85-4e8d-b9ac-c1ae9cba5c89)

**Comment by KhamisiKibet** [comment]
yeah, that's normal. I tested it on a dark themed pc, but you can solve
that problem using qt stylesheet to set the text color
