### ISSUE TITLE
Building Issue, Again

### ISSUE THREAD

**Issue by pdnguyen179** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#62]
I got issue when build project with auto-py-to-exe
I choosed One-file mode and got this error when run my application :
AttributeError: 'MainWindow' object has no attribute 'orginazationName'
How can i pass this???

**Comment by KhamisiKibet** [comment]
Check your json file. It should contain the app name, url, organization name... for you to use QSettings

**Comment by pdnguyen179** [comment]
> Check your json file. It should contain the app name, url, organization name... for you to use QSettings

Still not working

**Comment by pdnguyen179** [comment]
![Untitled](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/126751109/db670988-e9c0-48c3-8630-f985171f5c2c)
![Untitled2](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/126751109/932297e0-19e8-42f9-a13c-3bf44dca8bf3)
@KhamisiKibet
