### ISSUE TITLE
problems with style.json

### ISSUE THREAD

**Issue by KirillDolgopyatov** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#63]
after i added
**loadJsonStyle(i, self.ui)**
and ran the code, a window like yours appeared, but I can't close or move it

please tell me what is wrong??

![111](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/112104772/4b416bff-b804-4930-8ca9-cd63111cbc0e)
![1](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/112104772/e9117e6c-0267-4113-9c1c-4701cff9c1e5)
![2](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/112104772/57cf64bd-47b9-466e-804f-d24f1b14bc77)

**Comment by d0loresh4z3** [comment]
**I just loaded the jsonstyle, and the code looks like this:
```
import os
import sys
from ui_interface_oficial import *
from Custom_Widgets.Widgets import *

class MainWindow(QMainWindow): 
	def __init__(self, parent=None):
		QMainWindow.__init__(self)
		self.ui = Ui_MainWindow()
		self.ui.setupUi(self)

		loadJsonStyle(self, self.ui)

		self.show()

if __name__ == "__main__":
	app = QApplication(sys.argv)
	window = MainWindow()
	window.show()
	sys.exit(app.exec_())
```

But its showing this error: 
```
Traceback (most recent call last):
  File "C:\Users\Jesus\Downloads\GUI\main.py", line 18, in <module>
    window = MainWindow()
  File "C:\Users\Jesus\Downloads\GUI\main.py", line 10, in __init__
    self.ui.setupUi(self)
  File "C:\Users\Jesus\Downloads\GUI\ui_interface_oficial.py", line 52, in setupUi
    self.centralwidget = QWidget(MainWindow)
TypeError: 'PySide2.QtWidgets.QWidget' called with wrong argument types:
  PySide2.QtWidgets.QWidget(MainWindow)
Supported signatures:
  PySide2.QtWidgets.QWidget(typing.Optional[PySide2.QtWidgets.QWidget] = None, PySide2.QtCore.Qt.WindowFlags = Default(Qt.WindowFlags))
```**

**Comment by KhamisiKibet** [comment]
Share your json file

**Comment by KhamisiKibet** [comment]
does your json file names match with your ui widget names?

**Comment by d0loresh4z3** [comment]
I fixed it by adding this code line in the ui interface code: 
`from Custom_Widgets.Widgets import *`

**Comment by KirillDolgopyatov** [comment]
yes thank you it worked !

> Я исправил это, добавив эту строку кода в код интерфейса пользовательского интерфейса: `from Custom_Widgets.Widgets import *`

**Comment by KirillDolgopyatov** [comment]
> But its showing this error:

try adding from Custom_Widgets.Widgets import * to the file ui_new.python

![image](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/112104772/a39b5553-646f-459d-b0ba-82e406e06a94)
