### ISSUE TITLE
'PySide2.QtWidgets.QWidget' called with wrong argument

### ISSUE THREAD

**Issue by KofanovE** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#64]
Hi! On Ubuntu (Python3.7, PyQt5, PySide2)  or Windows10, I have same mistake:

File "main.py", line 66, in <module>
  window = MainWindow()
 File "main.py", line 31, in __init__
   self.ui.setupUi(self)
 File "C:\Users\админ\GUI_SQL\ui_interface.py", line 53, in setupUi
    self.centralwidget = QWidget(MainWindow)
TypeError: 'PySide2.QtWidgets.QWidget' called with wrong argument types:
  PySide2.QtWidgets.QWidget(MainWindow)
Supported signatures:
  PySide2.QtWidgets.QWidget(typing.Union[PySide2.QtWidgets.QWidget, NoneType] = None, PySide2.QtCore.Qt.WindowFlags = Default(Qt.WindowFlags))

Maybe, anybody had same problem, and know, what to do?

**Comment by d0loresh4z3** [comment]
I got the same error but i dont know how to fix it
