### ISSUE TITLE
issue erros cairocffi , how to fix 

### ISSUE THREAD

**Issue by truyenle-cietrading** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#65]
\AppData\Local\Programs\Python\Python310\lib\site-packages\cairocffi\__init__.py", line 44, in dlopen      
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

->> i use PySide6 and newbie stupid

**Comment by KhamisiKibet** [comment]
The issue is already solved. Check closed issues or visit the YouTube channel page.
