### ISSUE TITLE
Error when adding the json file

### ISSUE THREAD

**Issue by d0loresh4z3** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#66]
Good work. Keep on doing these amazing videos. 
Can you help me with my code? I keep on getting the same mistake just at the moment i added the loadJsonStyle(self, self.ui) and from Custom_Widgets.Widgets import *.

This is the notification error that I keep on getting is this one:
Traceback (most recent call last):
  File "C:\Users\Jesus\Downloads\GUI\main.py", line 19, in <module>
    window = MainWindow()
  File "C:\Users\Jesus\Downloads\GUI\main.py", line 12, in _init_
    self.ui.setupUi(self)
  File "C:\Users\Jesus\Downloads\GUI\ui_interface_oficial.py", line 52, in setupUi
    self.centralwidget = QWidget(MainWindow)
TypeError: 'PySide2.QtWidgets.QWidget' called with wrong argument types:
  PySide2.QtWidgets.QWidget(MainWindow)
Supported signatures:
  PySide2.QtWidgets.QWidget(typing.Optional[PySide2.QtWidgets.QWidget] = None, PySide2.QtCore.Qt.WindowFlags = Default(Qt.WindowFlags))

**Comment by ayalaortizoscarivan** [comment]
I have the same problem.

**Comment by d0loresh4z3** [comment]
Well, i fixed it by adding this code line in the ui interface code: 
`from Custom_Widgets.Widgets import *`
