### ISSUE TITLE
'Ui_MainWindow' object had no attribute 'themes'

### ISSUE THREAD

**Issue by pdnguyen179** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#68]
![Untitled](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/126751109/e7ba8e04-6741-4ab9-8e49-421411af44c7)
I used auto-py-to-exe with one-file mode, how to fix this pls?
I used to ask many time but still haven't any idea!

**Comment by KhamisiKibet** [comment]
Check this repository for help on how to use custom widgets: https://github.com/KhamisiKibet/Qt-Project-Creater-Modern-GUI
