### ISSUE TITLE
error loading json file 

### ISSUE THREAD

**Issue by trilogy0fg** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#69]
i get this error when running the code, i named json file style.json  and i did install gtk3

>   File "c:\Users\Desktop\automatisation\main.py", line 17, in <module>
      window = MainWindow()
>   File "c:\UsersDesktop\automatisation\main.py", line 12, in __init__
      loadJsonStyle(self, self.ui)
>   File "C:\Users\Programs\Python\Python39\lib\site-packages\Custom_Widgets\Widgets.py", line 1492, in loadJsonStyle
     applyJsonStyle(self, self.ui, data)
    File "C:\Users\Programs\Python\Python39\lib\site-packages\Custom_Widgets\Widgets.py", line 2104, in applyJsonStyle
      containerWidget.customizeQCustomSlideMenu(
>   File "C:\Users\Programs\Python\Python39\lib\site-packages\Custom_Widgets\Widgets.py", line 1125, in customizeQCustomSlideMenu
      self.refresh()
>   File "C:\Users\Programs\Python\Python39\lib\site-packages\Custom_Widgets\Widgets.py", line 1359, in refresh
      if self.isExpanded():
>   File "C:\Users\Programs\Python\Python39\lib\site-packages\Custom_Widgets\Widgets.py", line 1375, in isExpanded
      if self.width() > self.getCollapsedWidth() or self.width() > self.getCollapsedHeight():
> TypeError: '>' not supported between instances of 'int' and 'NoneType'

**Comment by KhamisiKibet** [comment]
Check the name of your widget
