### ISSUE TITLE
ModuleNotFoundError: No module named 'Custom_Widgets.__init__.Qss'

### ISSUE THREAD

**Issue by hobik** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#72]
Before the convert .exe, main-qr.py working successfuly without any error but after convert the onefile exe with pyinstaller and try to open I got this error:

```
>main-qr
Traceback (most recent call last):
  File "main-qr.py", line 4, in <module>
    from Custom_Widgets.Widgets import *
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "Custom_Widgets\Widgets.py", line 3, in <module>
  File "C:\Users\Duygu\AppData\Local\Temp\embedded.oon059l_.zip\shibokensupport\__feature__.py", line 142, in _import
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "Custom_Widgets\QCustomProgressIndicator.py", line 20, in <module>
  File "C:\Users\Duygu\AppData\Local\Temp\embedded.oon059l_.zip\shibokensupport\__feature__.py", line 142, in _import
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "Custom_Widgets\__init__.py", line 16, in <module>
  File "C:\Users\Duygu\AppData\Local\Temp\embedded.oon059l_.zip\shibokensupport\__feature__.py", line 142, in _import
ModuleNotFoundError: No module named 'Custom_Widgets.__init__.Qss'
[4852] Failed to execute script 'main-qr' due to unhandled exception!
```
I need solutions but I cant can you help me?

**Comment by KhamisiKibet** [comment]
Did you solve it?

**Comment by Xenon98** [comment]
Downgrading the version of QT-PyQt-PySide-Custom-Widgets from 0.6.8 to 0.6.7 works for me.

**Comment by Saray161** [comment]
I have the same error, I can't solve it in any way. Can anyone help?

**Comment by Saray161** [comment]
I have 

> Downgrading the version of QT-PyQt-PySide-Custom-Widgets from 0.6.8 to 0.6.7 works for me.

it didn't work for Pyside 6

**Comment by zhiluo20** [comment]
HI, I got the same error here. it seems that pyinstaller cannot hook  Custom_Widgets model correctly, and according to the error message, problem was in __init__file of  Custom_Widgets model. 

So, I checked __init__.py in Custom_Widgets model, and it shows "from .Qss import SassCompiler" , "from .Qss.SvgToPngIcons import NewIconsGenerator" , "from .QCustomQPushButtonGroup import QCustomQPushButtonGroup" and "from  .QCustomQPushButton import applyAnimationThemeStyle, applyButtonShadow, iconify, applyCustomAnimationThemeStyle, applyStylesFromColor"

 **I think the way __init__.py imports submodels cause this problem,** so I changed import way from "from .Qss import SassCompiler" to "from Custom_Widgets.Qss import SassCompiler" (change all relative imports) and problem solved for me.

**Comment by Saray161** [comment]
> Привет, у меня такая же ошибка. кажется, что pyinstaller не может правильно подключить модуль Custom_Widgets, и, согласно сообщению об ошибке, проблема была в __init__file модуля Custom_Widgets.
> 
> Итак, я проверил **init** .py в модуле Custom_Widgets, и он показывает «из .Qss import SassCompiler», «из .Qss.SvgToPngIcons import NewIconsGenerator», «из .QCustomQPushButtonGroup import QCustomQPushButtonGroup» и «из .QCustomQPushButton import applyAnimationThemeStyle, applyBut tonShadow, иконизировать , applyCustomAnimationThemeStyle, applyStylesFromColor"
> 
> **Я думаю, что способ импорта подмодулей init.py вызывает эту проблему,** поэтому я изменил способ импорта с «из .Qss import SassCompiler» на «из Custom_Widgets.Qss import SassCompiler» (изменить все относительные импорты), и проблема решена для меня.


Спасибо за ответ. В моем случае, я в init.py упомянул все варианты на Custom_Widgets.(имя_библиотеки). 

from Custom_Widgets.Qss import SassCompiler
# from .Qss import SassCompiler
CompileStyleSheet = SassCompiler.CompileStyleSheet
from  Custom_Widgets.Qss.SvgToPngIcons import NewIconsGenerator
from  Custom_Widgets.QCustomQPushButtonGroup import QCustomQPushButtonGroup

После этого все собралось.

**Comment by MiguelRoncagliolo** [comment]
Is there another solution? I tried changing the imports submodules, but I keep getting the same error.

**Comment by zhiluo20** [comment]
Did you check ALL submodules and change ALL submodules imports？ if it shows the same error after changing， you might miss some submodules or there might be some submodules that are still not changed. Just try checking each line of imports carefully， and see if problem will be fixed.

**Comment by zhiluo20** [comment]
> Is there another solution? I tried changing the imports submodules, but I keep getting the same error.

Did you check ALL submodules and change ALL submodules imports？ if it shows the same error after changing， you might miss some submodules or there might be some submodules that are still not changed. Just try checking each line of imports carefully， and see if problem will be fixed.
