### ISSUE TITLE
type error when running project

### ISSUE THREAD

**Issue by JavadKhanloo** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#77]
hi, thankyou for creating this usefull module
when i install your package and try to run projectmaker for custom_widgets
this user warning appeared:

########################################################################
RUNNING YOUR PROJECT
########################################################################

C:\Users\pc\AppData\Local\Programs\Python\Python38\lib\site-packages\Custom_Widgets\Widgets.py:10: UserWarning: Deprecated imports. Please update your import statements.
For more information, refer to the documentation at: https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets or contact support.
  warnings.warn(
FIXME Subscripted generics cannot be used with class and instance checks
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    window = MainWindow()
  File "main.py", line 31, in __init__
    self.ui.setupUi(self)
  File "C:\Users\pc\Desktop\gui\project_maker\ui_interface.py", line 53, in setupUi
    self.centralwidget = QWidget(MainWindow)
TypeError: 'PySide2.QtWidgets.QWidget' called with wrong argument types:
  PySide2.QtWidgets.QWidget(MainWindow)
Supported signatures:
  PySide2.QtWidgets.QWidget(typing.Union[PySide2.QtWidgets.QWidget, NoneType] = None, PySide2.QtCore.Qt.WindowFlags = Default(Qt.WindowFlags))

**Comment by JavadKhanloo** [comment]
please help me to solve this problem

**Comment by JavadKhanloo** [comment]
and please tell me what best version for libraries and python
for example pyside

**Comment by klosto** [comment]
Hi,
optimally use library named qtpy. For some reason it's the only one, which works for me.

**Comment by JavadKhanloo** [comment]
thanks a lot for your answer.
but i don't know how to use this library.
would you mind if tell me how to use qtpy library!!!

**Comment by klosto** [comment]
> thanks a lot for your answer.
> but i don't know how to use this library.
> would you mind if tell me how to use qtpy library!!!

The qtpy library works same as PySide2 or PyQt5 library. For example when you import QtWidgets, just type:
`from qtpy.QtWidgets import *`

**Comment by JavadKhanloo** [comment]
dear klosto 
i was copied "from qtpy.QtWidgets import *" in the interface.py and my problem was solved.
thank you
