### ISSUE TITLE
Unable to import required Qt libraries from PySide2! 

### ISSUE THREAD

**Issue by 7bao** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#78]
Unable to import required Qt libraries from PySide2! Please set the 'ICONIFY_QTLIB' env var to the location of a Qt5 compliant python binding you would like to use.
i use pyside6 not pyside2 how to fix it.  the version is 0.6.8; pyside version is 6.6.0; iconify is 0.0.103;

**Comment by aileenfun** [comment]
same problem, same error, please help

**Comment by klosto** [comment]
Hi,
I recommend to use library named qtpy - just import all from that library and problem will be probably solved.

**Comment by KhamisiKibet** [comment]
Use the latest custom widgets that uses qtpy
