### ISSUE TITLE
 The following error occurred. Why?

### ISSUE THREAD

**Issue by Sungwook-Jang** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#8]
>>> from Custom_Widgets import ProjectMaker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\anaconda3\envs\venv_test\lib\site-packages\Custom_Widgets\ProjectMaker.py", line 14, in <module>
    import cairosvg
  File "C:\anaconda3\envs\venv_test\lib\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
  File "C:\anaconda3\envs\venv_test\lib\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\anaconda3\envs\venv_test\lib\site-packages\cairocffi\__init__.py", line 50, in <module>
    ('libcairo.so.2', 'libcairo.2.dylib', 'libcairo-2.dll'))
  File "C:\anaconda3\envs\venv_test\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

Is it a Windows OS error?

**Comment by projectintel-anon** [comment]
> I got this error as well, did u find any fix?

Yes. Check my open pull request. OP hasn't pushed it to main yet. It fixes this issue.

**Comment by projectintel-anon** [comment]
> > > > from Custom_Widgets import ProjectMaker
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "C:\anaconda3\envs\venv_test\lib\site-packages\Custom_Widgets\ProjectMaker.py", line 14, in 
> > > > import cairosvg
> > > > File "C:\anaconda3\envs\venv_test\lib\site-packages\cairosvg__init__.py", line 26, in 
> > > > from . import surface  # noqa isort:skip
> > > > File "C:\anaconda3\envs\venv_test\lib\site-packages\cairosvg\surface.py", line 9, in 
> > > > import cairocffi as cairo
> > > > File "C:\anaconda3\envs\venv_test\lib\site-packages\cairocffi__init__.py", line 50, in 
> > > > ('libcairo.so.2', 'libcairo.2.dylib', 'libcairo-2.dll'))
> > > > File "C:\anaconda3\envs\venv_test\lib\site-packages\cairocffi__init__.py", line 45, in dlopen
> > > > raise OSError(error_message)  # pragma: no cover
> > > > OSError: no library called "cairo-2" was found
> > > > no library called "cairo" was found
> > > > no library called "libcairo-2" was found
> > > > cannot load library 'libcairo.so.2': error 0x7e
> > > > cannot load library 'libcairo.2.dylib': error 0x7e
> > > > cannot load library 'libcairo-2.dll': error 0x7e
> 
> Is it a Windows OS error?

Yes it is. OP wrote this project in Ubuntu, and had no framework for Windows or macOS. My open pull request fixes all Windows problems.

**Comment by KhamisiKibet** [comment]
Install **GTK+ for Windows Runtime Environment Installer: 64-bit** to solve [Cairo SVG](https://pypi.org/project/CairoSVG/) problem on windows.
Download it from here: _https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer_

Restart your text editor or pc after installing and everything should run fine.

**Comment by projectintel-anon** [comment]
> Install **GTK+ for Windows Runtime Environment Installer: 64-bit** to solve [Cairo SVG](https://pypi.org/project/CairoSVG/) problem on windows.
> Download it from here: _https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer_
> 
> Restart your text editor or pc after installing and everything should run fine.

Even after doing this, there are multiple errors which occur in your setup.py when trying to install, one example being that the dependencies you list in the file are for Debian-based OS; half of those dependencies are included in the STDLIB on Windows.

Can you also comment on why have not approved and merged my pull request after acknowledging it 2 weeks ago or more?

Thanks.

**Comment by Yunting-Zhao** [comment]
I have solved this problem by doing below， but the only and ultimately important difference is that you need to move the location of GTK+ (which you have installed) in the system environment variables to the top, in order for python to accurately retrieve the valid dll file. 

Install GTK+ for Windows Runtime Environment Installer: 64-bit to solve [Cairo SVG](https://pypi.org/project/CairoSVG/) problem on windows.
Download it from here: https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer

Restart your text editor or pc after installing and everything should run fine.

**Comment by jhonlima97** [comment]
> He resuelto este problema haciendo lo siguiente, pero la única y en última instancia importante diferencia es que necesita mover la ubicación de GTK + (que ha instalado) en las variables de entorno del sistema a la parte superior, para que python recupere con precisión el archivo dll válido.
> 
> Instalar GTK+ para Windows Runtime Environment Installer: 64 bits para resolver el problema [de Cairo SVG](https://pypi.org/project/CairoSVG/) en Windows. Descárgalo desde aquí: https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer
> 
> Reinicie su editor de texto o PC después de la instalación y todo debería funcionar bien.



> He resuelto este problema haciendo lo siguiente, pero la única y en última instancia importante diferencia es que necesita mover la ubicación de GTK + (que ha instalado) en las variables de entorno del sistema a la parte superior, para que python recupere con precisión el archivo dll válido.
> 
> Instalar GTK+ para Windows Runtime Environment Installer: 64 bits para resolver el problema [de Cairo SVG](https://pypi.org/project/CairoSVG/) en Windows. Descárgalo desde aquí: https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer
> 
> Reinicie su editor de texto o PC después de la instalación y todo debería funcionar bien.



> > Install **GTK+ for Windows Runtime Environment Installer: 64-bit** to solve [Cairo SVG](https://pypi.org/project/CairoSVG/) problem on windows.
> > Download it from here: _https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer_
> > Restart your text editor or pc after installing and everything should run fine.
> 
> Even after doing this, there are multiple errors which occur in your setup.py when trying to install, one example being that the dependencies you list in the file are for Debian-based OS; half of those dependencies are included in the STDLIB on Windows.
> 
> Can you also comment on why have not approved and merged my pull request after acknowledging it 2 weeks ago or more?
> 
> Thanks.

All correct, thank you very much

**Comment by jhonlima97** [comment]
All correct, thank you very much🖥💻W10
