### ISSUE TITLE
'MainWindow' object has no attribute 'orginazationName

### ISSUE THREAD

**Issue by zxbz12345** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#80]
run:QAppSettings.updateAppSettings(self)
AttributeError: 'MainWindow' object has no attribute 'orginazationName'
Have you seen one?

**Comment by klosto** [comment]
Hi,
could you post here your code?

**Comment by MiguelRoncagliolo** [comment]
Is there any solution for this problem? Even doing some changes on json file and AppSettings dosent do anything
@KhamisiKibet

**Comment by KhamisiKibet** [comment]
use self.orginazationName = str()

Check your json objects
https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/tree/main/examples/PySide6/QAppSettings
