### ISSUE TITLE
No module named 'iconify'

### ISSUE THREAD

**Issue by C3EQUALZz** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#83]
Hello, I have a problem with any code from your project. If I run in Pycharm  `from Custom_Widgets.ProgressIndicator import test test.main()` then I will have this error. Also if I run in termial `from Custom_Widgets import ProjectMaker` then have such problem. I have Python 3.12 installed and OS - Fedora 39. On Python version 3.11, the same problem. Your review on which I tried to do something: [https://youtu.be/X8fY8uFgzb4?si=Rc1qcguS6S8EQpVH](url)

![изображение](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/97458127/f483c276-71b1-439c-8488-bbf9092ed7de)
 
![изображение](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/97458127/55a79f25-3843-4bb5-860c-f9d3cc919231)

**Comment by klosto** [comment]
Hi,
try to update CustomWidgets.
```
pip install --upgrade QT-PyQt-PySide-Custom-Widgets
```

**Comment by C3EQUALZz** [comment]
Updated, same problem

**Comment by HM-Layla** [comment]
I encountered a similar issue.
Try to resolve it by executing the command `pip install iconify`.

**Comment by C3EQUALZz** [comment]
It is very unusual that the author has the same folder name as the module. I thought there was a problem with importing. Installing "iconify" helpls me. Also I installed PySide6. Author, unfortunately, did not write dependencies in requirements.txt.... Thanks for the help.
