### ISSUE TITLE
UserWarning: Deprecated imports. Please update your import statements

### ISSUE THREAD

**Issue by MuhammadSibtain5099** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#85]
C:\Users\MuhammadSibtain\.conda\envs\yolov8_new\lib\site-packages\Custom_Widgets\Widgets.py:10: UserWarning: Deprecated imports. Please update your import statements.
For more information, refer to the documentation at: https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets or contact support.
  warnings.warn(

**Comment by icboys** [comment]
This is just a warning, if you don't want to show above message, you can go to the Custom_Widgets\Widgets.py and deleted the statement. 

import warnings
warnings.warn(
    "Deprecated imports. Please update your import statements.\n"
    "For more information, refer to the documentation at: "
    "https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets "
    "or contact support."
)

**Comment by KhamisiKibet** [comment]
Thats just warning. Read the documentation or the latest changes, especially the import statements.
