### ISSUE TITLE
Custom_Widgets EM: No Module named ‘iconify’

### ISSUE THREAD

**Issue by Cshea23** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#87]
Mac osx
M1

homebrew pyqt6
Pycharm 

when trying to run the project maker or after manually creating main.py im unable to find iconify module.

Pip install iconify does not work as subsequent errors are produced:
“Unable to import required QT libraries from Pyside2! Please set the ICON_QTLIB env var to the location of the qt5 compliant  python binding”

**Comment by KhamisiKibet** [comment]
update the custom widgets, it comes with its own modified version of iconify
