### ISSUE TITLE
ImportError: cannot import name 'Signal' from 'PyQt6.QtCore' (C:\Users\Schulaccount\AppData\Local\Programs\Python\Python39\lib\site-packages\PyQt6\QtCore.pyd)

### ISSUE THREAD

**Issue by TheChefkoch** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#89]
I have a problem with the QtCore. I don't know how to solve it.
I have installed PyQt6 and in the folder is QtCore included. 
![Screenshot 2023-12-31 121302](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/151154182/4dbb7b89-1c02-4e10-8ea6-27fd32c38e29)

**Comment by KhamisiKibet** [comment]
which version of custom widgets are you using?

**Comment by TheChefkoch** [comment]
I have the version 0.6.8. of the costum widgets.
I'm looking forward to hearing from you :)

**Comment by TheChefkoch** [comment]
> which version of custom widgets are you using?

The newest one 0.7.3.

That new version fixed the issue with import loadJsonStyle from CostumWidgets and the Signal import from QtCore, but something doesn't work with the QCustomSlideMenu. I looked in the modules, but can't find the error.

The new error message is:
![Screenshot](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/151154182/fe41b1a7-cea6-4773-be76-bc80e52a17f8)

**Comment by KhamisiKibet** [comment]
update the custom widgets
