### ISSUE TITLE
Some Questions in Installation

### ISSUE THREAD

**Issue by Yunting-Zhao** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#9]
My Environment : Windows 11 Pro , python 3.7.10, conda 4.11.0

When I use command "pip install QT-PyQt-PySide-Custom-Widgets" installing the pkgs, there is nothing happened. It's means everything is OK  (that what I thought).  But when I run the following code to see if the installation was successful.
-------------python 3.7.10
>>>from Custom_Widgets.ProgressIndicator import test

Lots of errors have occurred! Look like  this:

OSError: no library called "cairo-2" was found
no library called "cairo" was found
cannot load library 'D:\GTK2-Runtime Win64\bin\libcairo-2.dll': error 0x7f
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7f
----------------------------------------------------------------------------------
I spent my whole day trying to solve it, but I failed. Up to now, I even donot understand what's the problem is! It makes me desperate!

Below are the solution I have ever tryed:
pip install cairosvg
pip install cairocffi
Install  [GTK+ for Windows Runtime Environment Installer: 64-bit](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer)
Refer to [stackflow](https://stackoverflow.com/questions/28211418/python-oserror-cannot-load-library-libcairo-so-2)
install [uniconvertor-2.0rc4-win64_headless](https://sk1project.net/uc2/download/)

During this time, I restart my system a few times, but Nothing changed,

Hope someone could help me , Thanks a lot!

**Comment by Yunting-Zhao** [comment]
My Email Address: yunting_zhao@outlook.com

**Comment by KhamisiKibet** [comment]
The issue was solved here https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/issues/8#issuecomment-1059071881
