### ISSUE TITLE
ImportError: Unable to import required Qt libraries from pyside6! Please set the 'ICONIFY_QTLIB' env var to the location of a Qt5 compliant python binding you would like to use.

### ISSUE THREAD

**Issue by RobertArustamyan** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#92]
![Screenshot_2](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/143337237/4a69a79a-0129-447d-813d-a0385325f4a5)

This is the list of installed modules
cairocffi==1.6.1
CairoSVG==2.7.1    
certifi==2023.11.17
cffi==1.16.0       
chardet==3.0.4     
contourpy==1.2.0   
cssselect2==0.7.0  
cycler==0.12.1     
defusedxml==0.7.1  
fonttools==4.47.2  
iconify==0.0.103   
idna==2.10
kids.cache==0.0.7
kiwisolver==1.4.5
libsass==0.23.0
matplotlib==3.8.2
mock==5.1.0
numpy==1.26.3
packaging==23.2
pillow==10.2.0
pycparser==2.21
pyparsing==3.1.1
PyQt5==5.15.10
PyQt5-Qt5==5.15.2
PyQt5-sip==12.13.0
PySide6==6.6.1
PySide6-Addons==6.6.1
PySide6-Essentials==6.6.1
python-dateutil==2.8.2
QT-PyQt-PySide-Custom-Widgets==0.6.8
QtPy==2.4.1
qtsass==0.4.0
requests==2.23.0
shiboken6==6.6.1
six==1.16.0
tinycss2==1.2.1
typing==3.7.4
urllib3==1.25.11
webencodings==0.5.1

**Comment by BerndDasByte** [comment]
Yep same problem here, using Ubuntu 20.04 LTS.
`ImportError: Unable to import required Qt libraries from PySide2! Please set the 'ICONIFY_QTLIB' env var to the location of a Qt5 compliant python binding you would like to use.`

Installed packages:
```
cairocffi==1.6.1
CairoSVG==2.7.1
certifi==2023.11.17
cffi==1.16.0
chardet==3.0.4
contourpy==1.2.0
cssselect2==0.7.0
cycler==0.12.1
defusedxml==0.7.1
fonttools==4.47.2
iconify==0.0.103
idna==2.10
kids.cache==0.0.7
kiwisolver==1.4.5
libsass==0.23.0
matplotlib==3.8.2
mock==5.1.0
numpy==1.26.3
packaging==23.2
pillow==10.2.0
pycparser==2.21
pyparsing==3.1.1
PySide6==6.6.1
PySide6-Addons==6.6.1
PySide6-Essentials==6.6.1
python-dateutil==2.8.2
QT-PyQt-PySide-Custom-Widgets==0.6.8
QtPy==2.4.1
qtsass==0.4.0
requests==2.23.0
shiboken6==6.6.1
six==1.16.0
tinycss2==1.2.1
typing==3.7.4
urllib3==1.25.11
webencodings==0.5.1
```

**Comment by RobertArustamyan** [comment]
Do you find solution?

**Comment by Krayher** [comment]
@RobertArustamyan and @BerndDasByte 
You'll have to customize the Iconify Qt.py located at /Lib/site-packages/iconify/qt.py
replace PySide2 by PySide6 on imports.

It should look like this:

```
if TYPE_CHECKING:
    from PySide6 import QtCore, QtGui, QtSvg, QtWidgets, QtXml
    qtlib = 'PySide6'
else:
    qtlib = os.environ.get("I
CONIFY_QTLIB", "PySide6")
```

**Comment by KhamisiKibet** [comment]
Do not install multiple qt biding
