### ISSUE TITLE
Exception: side_menu is not a QCustomSlideMenu, no widget found

### ISSUE THREAD

**Issue by TheChefkoch** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#95]
I had a lot of errors of my programm and now it almost work, but the program has some problem with the side_menu and the QCostumSlideMenu. I don't know what to do. It's a bit frustrating when you've fixed some bugs and new ones pop up.I would be very happy if someone could help me.

Just for information: 

Package                       Version
----------------------------- ---------
async-timeout                 4.0.3
Brotli                        1.1.0
cairocffi                     1.6.1
CairoSVG                      2.7.1
certifi                       2024.2.2
cffi                          1.16.0
chardet                       3.0.4
click                         8.1.7
colorama                      0.4.6
contourpy                     1.2.0
cssselect2                    0.7.0
cycler                        0.12.1
defusedxml                    0.7.1
fonttools                     4.49.0
html5lib                      1.1
iconify                       0.0.103
idna                          2.10
importlib-resources           6.1.1
kids                          1.0.4
kids.cache                    0.0.7
kiwisolver                    1.4.5
libsass                       0.23.0
lxml                          5.1.0
matplotlib                    3.8.3
mock                          5.1.0
numpy                         1.26.4
packaging                     23.2
pillow                        10.2.0
pip                           24.0
pycairo                       1.26.0
pycparser                     2.21
pydyf                         0.8.0
pyparsing                     3.1.1
pyphen                        0.14.0
PyQt6                         6.4.2
pyqt6-plugins                 6.4.2.2.3
PyQt6-Qt6                     6.4.3
PyQt6-sip                     13.6.0
pyqt6-tools                   6.4.2.3.3
python-dateutil               2.8.2
python-dotenv                 1.0.1
QT-PyQt-PySide-Custom-Widgets 0.7.5
qt6-applications              6.4.3.2.3
qt6-tools                     6.4.3.1.3
QtPy                          2.4.1
qtsass                        0.4.0
redis                         5.0.1
requests                      2.23.0
setuptools                    58.1.0
six                           1.16.0
termcolor                     2.4.0
tinycss2                      1.2.1
typing                        3.7.4
urllib3                       1.25.11
watchdog                      4.0.0
weasyprint                    61.0
webencodings                  0.5.1
zipp                          3.17.0
zopfli                        0.2.3

![errormessage](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/151154182/985ed377-6ae4-4a60-a606-724f51f0ef61)
![main](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/151154182/dcd7600e-e312-43ee-aa61-de89be677b22)
![pycharmdatastructure](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/151154182/eb0d2e72-1117-40e9-bdb9-98b8e48958e7)

**Comment by KhamisiKibet** [comment]
You need to promote your widget, follow the documentation

**Comment by TheChefkoch** [comment]
I solved the problem by rewriting the main that's like the same code as yours.
![Screenshot 2024-03-01 133355](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/151154182/fd7d6a62-b05b-4675-b30f-19476a4f5dd8)

**Comment by TheChefkoch** [comment]
Do you know how I can call from a parent StackedWidgets a page from a child StackedWidgets?

**Comment by KhamisiKibet** [comment]
You need to promote the widget: https://khamisikibet.github.io/Docs-QT-PyQt-PySide-Custom-Widgets/docs/widgets/custom-slide-menu-widgets
