### ISSUE TITLE
ImportError: cannot import name 'QLabelThemed' from 'Custom_Widgets.Theme' 

### ISSUE THREAD

**Issue by TheHaterNoob** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#97]
Getting this error:
Using Mac OS
---> 23 from Custom_Widgets.Theme import (QLabelThemed, QPushButtonThemed)
     24 from Custom_Widgets.Widgets import (QCustomSlideMenu, QCustomStackedWidget)
     26 class Ui_MainWindow(object):

ImportError: cannot import name 'QLabelThemed' from 'Custom_Widgets.Theme' ([/usr/local/Cellar/jupyterlab/4.1.4/libexec/lib/python3.12/site-packages/Custom_Widgets/Theme/__init__.py](http://localhost:8889/usr/local/Cellar/jupyterlab/4.1.4/libexec/lib/python3.12/site-packages/Custom_Widgets/Theme/__init__.py))

**Comment by KhamisiKibet** [comment]
Update the custom widgets, then convert your UI files using the command from the custom widgets module:

The commands are here https://khamisikibet.github.io/Docs-QT-PyQt-PySide-Custom-Widgets/docs/new-features

**Comment by spyhabs** [comment]
The link doesn't work at all! :(
